In [1]:
import os
import time
import shutil
import numpy as np
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.utils as utils
import torch.nn.init as init
from torchvision import datasets

In [2]:
data_type = 'mic'
model_num = 2
time_len =  20  ## ms
point_len = int(time_len*10)
div_num = int(100*(20/time_len))
vow_num = int(div_num/5)

fc_len = int(point_len/32)+1

In [3]:
class Model(nn.Module):
    def __init__(self, loss):
        super(Model, self).__init__()
        prob = 0.8
        input_c = 10
        channel = 32
        self.conv1 = nn.Sequential(
            nn.Conv1d(input_c, channel, kernel_size=5, stride=2, padding=2),
#             nn.Dropout(p=prob),
            nn.LeakyReLU(negative_slope=0.1),
            nn.BatchNorm1d(channel))
        self.conv2 = nn.Sequential(
            nn.Conv1d(channel, channel*2, kernel_size=5, stride=2, padding=2),
#             nn.Dropout(p=prob),
            nn.LeakyReLU(negative_slope=0.1),
            nn.BatchNorm1d(channel*2))
        self.conv3 = nn.Sequential(
            nn.Conv1d(channel*2, channel*2, kernel_size=5, stride=2, padding=2),
#             nn.Dropout(p=prob),
            nn.LeakyReLU(negative_slope=0.1),
            nn.BatchNorm1d(channel*2))
        self.conv4 = nn.Sequential(
            nn.Conv1d(channel*2, channel*4, kernel_size=5, stride=2, padding=2),
#             nn.Dropout(p=prob),
            nn.LeakyReLU(negative_slope=0.1),
            nn.BatchNorm1d(channel*4))
        self.conv5 = nn.Sequential(
            nn.Conv1d(channel*4, channel*4, kernel_size=5, stride=2, padding=2),
#             nn.Dropout(p=prob),
            nn.LeakyReLU(negative_slope=0.1),
            nn.BatchNorm1d(channel*4))
        self.fc1 = nn.Sequential(
            nn.Linear(channel*4*fc_len, 1024),
#             nn.Dropout(p=prob),
            nn.LeakyReLU(negative_slope=0.1),
            nn.BatchNorm1d(1024))
        self.fc2 = nn.Sequential(
            nn.Linear(1024, 5),
            nn.Softmax(dim=1))
        self.loss = loss
        
    def forward(self, data, target):
        x = self.conv1(data)
#         print('1',x.size())
        x = self.conv2(x)
#         print('2',x.size())
        x = self.conv3(x)
#         print('3',x.size())
        x = self.conv4(x)
#         print('4',x.size())
        x = self.conv5(x)
#         print('5',x.size())
        x = x.view(x.size()[0],-1)
        x = self.fc1(x)
#         print('8',x.size())
        h = self.fc2(x)
#         print('9',h.size())
        
        l = self.loss(h, target)
        return l, h, target

In [4]:
def train(model, trainX, trainY, batch, device, optimizer, train_loss, train_acc):
    model.train()
    dloss = 0
    dacc = 0
    
    rand = torch.randperm(trainX.size()[0])
    trainX = trainX[rand]
    trainY = trainY[rand]
    
    for i in range(batch[0]):
        optimizer.zero_grad()
        loss, output, target = model(trainX[i*batch[1]:(i+1)*batch[1]], trainY[i*batch[1]:(i+1)*batch[1]])
        loss = loss.sum()
        loss.backward()
        optimizer.step()
        
        _, output = torch.max(output, 1)
        _, target = torch.max(target, 1)

        dloss += loss.cpu().item()
        dacc += (output==target).sum().item()
        
    train_loss.append(dloss/batch[0])
    train_acc.append(dacc/(batch[0]*batch[1]))
    return train_loss, train_acc

def test(model, testX, testY, device, test_loss, test_acc):
    model.eval()
    loss, output, target = model(testX, testY)
    loss = loss.sum()
    
    _, output = torch.max(output, 1)
    _, target = torch.max(target, 1)
    
    test_loss.append(loss.cpu().item())
    test_acc.append((output==target).sum().item()/len(testX))
    return test_loss, test_acc, output, target

In [9]:
if __name__=='__main__':
    print('[Training]%s_%.1f_model%d'%(data_type, time_len, model_num))
    ch_list = [0,2,4,6,8,10,12,14,16,18]
    torch.manual_seed(37)
    torch.cuda.manual_seed_all(37)
    torch.backends.cudnn.deterministic = True
    
    trainX = np.load('npy_data/%s/19ch_%.1fms_trainX.npy'%(data_type, time_len))[:,ch_list,:]
    trainY = np.load('npy_data/%s/19ch_%.1fms_trainY.npy'%(data_type, time_len))
    testX = np.load('npy_data/%s/19ch_%.1fms_testX.npy'%(data_type, time_len))[:,ch_list,:]
    testY = np.load('npy_data/%s/19ch_%.1fms_testY.npy'%(data_type, time_len))

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    
    batch_num = 1000
    batch = [int(len(trainX)/batch_num), batch_num]
    
    trainX = torch.Tensor(trainX).to(device)
#     _, trainY = torch.max(torch.LongTensor(trainY).to(device), 1)
    trainY = torch.Tensor(trainY).to(device)
    testX = torch.Tensor(testX).to(device)
    testY = torch.Tensor(testY).to(device)
#     _, testY = torch.max(torch.LongTensor(testY).to(device), 1)
    print('mem data shape  -  %.1f ms'%time_len)
    print('train set :', np.shape(trainX) , np.shape(trainY))
    print('test set :', np.shape(testX) ,np.shape(testY))
    
    
    learning_rate = 0.0002
    loss_func=nn.BCELoss()
    model = nn.DataParallel(Model(loss_func)).to(device)
#     model = Model(loss_func).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=batch_num, eta_min = 3e-6)

#     model.load_state_dict(torch.load('ckpt/model%d/%s/%.1f_ckpt_100.pt'%(model_num, data_type, time_len)))
    a = time.time()
    train_loss = []
    train_acc = []
    test_loss = []
    test_acc = []
    for epoch in range(1001):
        train_loss, train_acc = train(model, trainX, trainY, batch, device, optimizer, train_loss, train_acc)
        test_loss, test_acc, output, target = test(model, testX, testY, device, test_loss, test_acc)
        scheduler.step()
        
        if epoch%10==0:
            vowel_check = (output==target).cpu().detach().numpy()
            vowel_acc = np.zeros(5)
            for k1 in range(15):
                for k2 in range(5):
                    vowel_acc[k2] += np.sum(vowel_check[div_num*k1 + vow_num*k2 : div_num*k1 + vow_num*(k2+1)])
            print(vowel_acc/(vow_num*15))
            print('epoch %d - train loss : %.7f  /  test loss : %.7f'%(epoch, train_loss[-1], test_loss[-1]))
            print('           train acc : %.7f  /  test acc : %.7f'%(train_acc[-1], test_acc[-1]))
#         if epoch%50==0:
#             print('@@@@@@@ save model : epoch %d'% epoch)
#             torch.save(model.state_dict(),'ckpt/model%d_%s/%.1f_ckpt_%d.pt'%(model_num, data_type, time_len, epoch))
#             np.savetxt('result/model%d_%s/%.1f_loss_tr.txt'%(model_num, data_type, time_len), train_loss)
#             np.savetxt('result/model%d_%s/%.1f_loss_te.txt'%(model_num, data_type, time_len), test_loss)
#             np.savetxt('result/model%d_%s/%.1f_acc_tr.txt'%(model_num, data_type, time_len), train_acc)
#             np.savetxt('result/model%d_%s/%.1f_acc_te.txt'%(model_num, data_type, time_len), test_acc)

    vowel_check = (output==target).cpu().detach().numpy()
    vowel_acc = np.zeros(5)
    for k1 in range(15):
        for k2 in range(5):
            vowel_acc[k2] += np.sum(vowel_check[div_num*k1 + vow_num*k2 : div_num*k1 + vow_num*(k2+1)])
    print(vowel_acc/(vow_num*15))
    print('epoch %d - train loss : %.7f  /  test loss : %.7f'%(epoch, train_loss[-1], test_loss[-1]))
    print('           train acc : %.7f  /  test acc : %.7f'%(train_acc[-1], test_acc[-1]))
    print("training complete! - calculation time :", time.time()-a, '  seconds')

[Training]mic_20.0_model2
mem data shape  -  20.0 ms
train set : torch.Size([5000, 10, 200]) torch.Size([5000, 5])
test set : torch.Size([1500, 10, 200]) torch.Size([1500, 5])
[0. 0. 1. 0. 0.]
epoch 0 - train loss : 0.8767160  /  test loss : 1.0009491
           train acc : 0.4612000  /  test acc : 0.2000000
[0.84       0.85       0.86666667 0.42333333 0.52333333]
epoch 10 - train loss : 0.1032831  /  test loss : 0.6420491
           train acc : 0.9720000  /  test acc : 0.7006667
[0.97666667 0.72       0.86       0.69666667 0.67666667]
epoch 20 - train loss : 0.0134282  /  test loss : 0.6263961
           train acc : 0.9998000  /  test acc : 0.7860000
[0.97       0.7        0.82666667 0.65666667 0.68666667]
epoch 30 - train loss : 0.0045620  /  test loss : 0.6908612
           train acc : 1.0000000  /  test acc : 0.7680000
[0.97333333 0.69       0.83       0.67333333 0.68666667]
epoch 40 - train loss : 0.0022149  /  test loss : 0.7350190
           train acc : 1.0000000  /  test acc : 

KeyboardInterrupt: 

In [10]:
print(np.max(np.loadtxt('result/model2/mfcc/20.0_acc_te.txt')))
print(np.max(np.loadtxt('result/model2/raw/20.0_acc_te.txt')))
print(np.max(np.loadtxt('result/model2/fft/20.0_acc_te.txt')))
print(np.max(np.loadtxt('result/model2/mem/20.0_acc_te.txt')))
print(np.argmax(np.loadtxt('result/model2/mfcc/20.0_acc_te.txt')))
print(np.argmax(np.loadtxt('result/model2/raw/20.0_acc_te.txt')))
print(np.argmax(np.loadtxt('result/model2/fft/20.0_acc_te.txt')))
print(np.argmax(np.loadtxt('result/model2/mem/20.0_acc_te.txt')))

0.846
0.8066666666666666
0.8266666666666667
0.8613333333333333
677
785
269
76


In [11]:
vowel_check = (output==target).cpu().detach().numpy()
vowel_acc = np.zeros(5)
for k1 in range(15):
    for k2 in range(5):
        vowel_acc[k2] += np.sum(vowel_check[div_num*k1 + vow_num*k2 : div_num*k1 + vow_num*(k2+1)])
print('whole accuracy :', vowel_acc/(vow_num*15))
            
vowel_check = (output==target).cpu().detach().numpy()
whole_count=np.array([])
for k1 in range(15):
    for k2 in range(5):
        if k2==3:
            aa = output[div_num*k1 + vow_num*k2 : div_num*k1 + vow_num*(k2+1)].cpu().detach().numpy()+1
            print(aa)
            bb = aa*((-1*np.int32(vowel_check[div_num*k1 + vow_num*k2 : div_num*k1 + vow_num*(k2+1)]))+1)
            whole_count = np.append(whole_count,bb)
unique, counts = np.unique(whole_count, return_counts=True)
#         vowel_acc[k2] += np.sum(vowel_check[div_num*k1 + vow_num*k2 : div_num*k1 + vow_num*(k2+1)])
print('\npart accuracy \n', dict(zip(unique, counts/(len(output)/5))))

whole accuracy : [0.95       0.69       0.82       0.67333333 0.67666667]
[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]
[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]
[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]
[2 2 3 3 2 2 2 3 3 3 2 2 2 3 2 2 2 2 2 2]
[5 4 4 4 4 5 4 4 4 4 4 4 4 4 4 4 4 4 4 4]
[5 5 5 4 5 4 4 4 5 5 4 4 5 5 4 5 5 5 5 5]
[4 4 5 4 4 5 4 4 5 5 5 5 4 5 5 4 4 4 5 5]
[5 4 2 4 4 4 4 4 4 2 5 4 5 4 2 4 2 2 2 4]
[4 4 5 4 4 4 4 4 5 5 5 4 5 4 4 4 4 4 4 4]
[4 4 4 4 5 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]
[5 4 5 4 4 4 4 4 5 4 4 4 4 5 5 4 4 5 4 4]
[4 4 4 4 5 4 4 5 4 4 5 5 4 5 4 4 4 4 4 4]
[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]
[4 4 5 4 4 4 4 5 4 4 5 4 5 4 4 4 5 5 4 5]

part accuracy 
 {0.0: 0.6733333333333333, 2.0: 0.06666666666666667, 3.0: 0.08666666666666667, 5.0: 0.17333333333333334}
